### ISSUE TITLE
Does not work on main branch

### ISSUE THREAD

**Issue by dotKuro** [yuya-takeyama/docker-tag-from-github-ref-action#171]
It works perfectly fine in PRs, but seems to crash when used after merging an pr to the main branch.

```
Run yuya-takeyama/docker-tag-from-github-ref-action@v1
  with:
    latest-branches: main,master
    remove-version-tag-prefix: true

/home/runner/work/_actions/yuya-takeyama/docker-tag-from-github-ref-action/v1/webpack:/typescript-action/lib/generate.js:24
    throw new Error(`Invalid "github.ref" format: ${githubRef}`);
^
Error: Invalid "github.ref" format: main
    at Object.exports.generate (/home/runner/work/_actions/yuya-takeyama/docker-tag-from-github-ref-action/v1/webpack:/typescript-action/lib/generate.js:24:1)
    at Object.109 (/home/runner/work/_actions/yuya-takeyama/docker-tag-from-github-ref-action/v1/webpack:/typescript-action/lib/main.js:26:1)
    at __webpack_require__ (/home/runner/work/_actions/yuya-takeyama/docker-tag-from-github-ref-action/v1/webpack:/typescript-action/webpack/bootstrap:20:1)
    at /home/runner/work/_actions/yuya-takeyama/docker-tag-from-github-ref-action/v1/webpack:/typescript-action/webpack/startup:4:1
    at Object.<anonymous> (/home/runner/work/_actions/yuya-takeyama/docker-tag-from-github-ref-action/v1/dist/index.js:6042:12)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10)
```

**Comment by yuya-takeyama** [comment]
I'm sorry but I'm no longer maintaining this repo
